### Importing **Numpy**

In [1]:
import numpy as np

### Checking Numpy version

In [2]:
np.version.version

'1.14.3'

In [3]:
np.__version__

'1.14.3'

### Creation

Creating two arrays:
* Python array
* Numpy array.

In [4]:
# python ordinary array
py_array = [0,1,2,3,4,5,6,7,8,9]

# numpy array
np_array = np.array([0,1,2,3,4,5,6,7,8,9])

Printing python array

In [5]:
print(py_array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Printing Numpy array

In [6]:
print(np_array)

[0 1 2 3 4 5 6 7 8 9]


### Type

In [17]:
type(py_array)

list

In [16]:
type(np_array)

numpy.ndarray

### Shape

In [18]:
# printing the length of python list/array
len(py_array)

10

In [19]:
# printing the length of numpy ndarray
len(np_array)

5

In [20]:
# printing the length of the outter array of np_matrix
len(np_matrix)

2

In [12]:
# create numpy array contains five elements
np_array = np.array([1, 2, 3, 4, 5])

# printing np_array shape(length per axis)
np_array.shape

(5,)

Shape of Matrix

In [13]:
# create numpy multi-dimensional array contains six elements(2 rows, 3 columns)
np_matrix = np.array([[1,2,3],[4,5,6]])

# printing np_matrix shape(length per axis/ number of rows and columns)
np_matrix.shape

(2, 3)

### `np.reshape()`

### `np.arrange()`

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,10) == np.arange(0,10,1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### np.zeros()

### np.ones()

### np.eye()

### np.dot()

### np.sum()

### Testing the speed

In [23]:
%%timeit
count = 0
for i in range(0, 1000):
    count = count + 1

45.2 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
%%timeit 
np_count = np.sum(np.ones((1000,), dtype=int), axis=0)

7.1 µs ± 47 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
count

1000

In [32]:
np_count

1000